#!/system/bin/sh
# lethe-tor-remote-dms — enable the remote-DMS Tor hidden service at boot.
#
# Reads persist.lethe.remote_dms.enabled and rewrites
# /data/lethe/tor/torrc.remote_dms with either:
#   - HiddenServiceDir + HiddenServicePort directives that publish
#     onion:80 -> 127.0.0.1:8081 (the agent's split-bind for remote_dms
#     routes; NEVER 127.0.0.1:8080 — that exposes the rest of the agent
#     surface), or
#   - an empty file (when disabled), which the main torrc's %include
#     still tolerates.
#
# The main torrc includes this fragment via `%include
# /data/lethe/tor/torrc.remote_dms`. The single Tor process publishes
# the hidden service when the prop is set; when it's unset, behavior is
# identical to today (transparent proxy only). See #103, lethe#172.
#
# Pair file gate is enforced separately at the agent layer — if no
# /data/lethe/remote_dms/pair.json is present, the agent doesn't bind
# 8081 and the hidden service publishes a target nothing answers.

set -e

ENABLED="$(getprop persist.lethe.remote_dms.enabled)"
FRAG="/data/lethe/tor/torrc.remote_dms"
TOR_DIR="/data/lethe/tor"

mkdir -p "$TOR_DIR"

case "$ENABLED" in
    1|true|TRUE)
        cat > "$FRAG" <<'EOF'
# Remote DMS / wipe-trigger hidden service (#103). Forwards onion:80
# to the agent's remote_dms-only bind (127.0.0.1:8081); the agent
# never exposes its primary 127.0.0.1:8080 surface here. v3 onion;
# key material is regenerated by Tor at first start.
HiddenServiceDir /data/lethe/tor/onion-dms/
HiddenServicePort 80 127.0.0.1:8081
HiddenServiceVersion 3
EOF
        log -t lethe-tor "remote_dms hidden service ENABLED"
        ;;
    *)
        : > "$FRAG"
        log -t lethe-tor "remote_dms hidden service disabled"
        ;;
esac

chmod 600 "$FRAG"
# Ownership left root:root — same justification as torrc.bridges in
# lethe-tor-pt-select.sh: Tor runs as root in v1.0/v1.1, mismatched
# ownership of files it reads would make it exit at startup.
